import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import { readFileSync } from "fs";
import { gzipSync } from "zlib";

// Node built-ins (and their "node:" prefixed forms) are provided by the
// Electron runtime, so they must stay external rather than being bundled.
const builtins = [...builtinModules, ...builtinModules.map((m) => `node:${m}`)];

// Inline the occt-import-js WASM as a gzipped base64 string rather than raw
// bytes. esbuild's "binary" loader base64-encodes the ~7.6 MB file as-is, which
// bloats main.js past 10 MB; gzipping first (WASM compresses ~2.5x) keeps the
// self-contained bundle under Obsidian Sync's 5 MB limit. OcctLoader inflates
// it once at runtime via DecompressionStream before handing it to emscripten.
const wasmGzipPlugin = {
  name: "wasm-gzip",
  setup(build) {
    build.onLoad({ filter: /occt-import-js\.wasm$/ }, (args) => {
      const gz = gzipSync(readFileSync(args.path), { level: 9 });
      return {
        contents: `export default ${JSON.stringify(gz.toString("base64"))};`,
        loader: "js",
      };
    });
  },
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  // Inline occt-import-js.wasm (gzipped, via wasmGzipPlugin). BRAT only fetches
  // main.js/manifest.json/styles.css from a release, so the WASM must be
  // self-contained rather than a separate file (design doc §6.1 alternative).
  plugins: [wasmGzipPlugin],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
