import esbuild from "esbuild";
import process from "process";
import path from "path";
import { builtinModules } from "module";
import { readFileSync } from "fs";
import { gzipSync } from "zlib";

// Node built-ins (and their "node:" prefixed forms) are provided by the
// Electron runtime, so they must stay external rather than being bundled.
const builtins = [...builtinModules, ...builtinModules.map((m) => `node:${m}`)];

const prod = process.argv[2] === "production";

const external = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtins,
];

// Inline the occt-import-js WASM as a gzipped base64 string rather than raw
// bytes. esbuild's "binary" loader base64-encodes the ~7.6 MB file as-is, which
// bloats main.js past 10 MB; gzipping first (WASM compresses ~2.5x) keeps the
// self-contained bundle under Obsidian Sync's 5 MB limit. OcctLoader inflates
// it once at runtime via DecompressionStream before handing it to emscripten.
const wasmGzipPlugin = {
  name: "wasm-gzip",
  setup(build) {
    build.onLoad({ filter: /occt-import-js\.wasm$/ }, (args) => {
      const gz = gzipSync(readFileSync(args.path), { level: 9 });
      return {
        contents: `export default ${JSON.stringify(gz.toString("base64"))};`,
        loader: "js",
      };
    });
  },
};

// Bundle `import code from "./x?worker"` into the worker's full IIFE source as a
// string. The worker runs the occt parse off the main thread; inlining its
// source (rather than shipping a separate file) keeps the plugin self-contained
// for BRAT. The worker does NOT import the .wasm — OcctLoader inflates it once
// on the main thread and posts it in, so the payload isn't embedded twice.
const inlineWorkerPlugin = {
  name: "inline-worker",
  setup(build) {
    build.onResolve({ filter: /\?worker$/ }, (args) => ({
      path: path.resolve(args.resolveDir, args.path.replace(/\?worker$/, "")),
      namespace: "inline-worker",
    }));
    build.onLoad({ filter: /.*/, namespace: "inline-worker" }, async (args) => {
      const result = await esbuild.build({
        entryPoints: [args.path],
        bundle: true,
        write: false,
        format: "iife",
        target: "es2020",
        platform: "browser",
        resolveExtensions: [".ts", ".js"],
        external,
        minify: prod,
        sourcemap: false,
        logLevel: "info",
      });
      return {
        contents: `export default ${JSON.stringify(result.outputFiles[0].text)};`,
        loader: "js",
        watchFiles: [args.path],
      };
    });
  },
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  // Inline occt-import-js.wasm (gzipped, via wasmGzipPlugin) and the occt worker
  // (via inlineWorkerPlugin). BRAT only fetches main.js/manifest.json/styles.css
  // from a release, so both must be self-contained (design doc §6.1 alternative).
  plugins: [wasmGzipPlugin, inlineWorkerPlugin],
  external,
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
