import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, existsSync } from "fs";
import { dirname } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outdir = ".";

/**
 * The occt-import-js WASM binary must sit next to main.js in the plugin
 * directory so OcctLoader can read it via the vault adapter at runtime.
 * See design doc §6.1.
 */
const copyWasmPlugin = {
  name: "copy-occt-wasm",
  setup(build) {
    build.onEnd(() => {
      const src = "node_modules/occt-import-js/dist/occt-import-js.wasm";
      const dest = `${outdir}/occt-import-js.wasm`;
      if (existsSync(src)) {
        mkdirSync(dirname(dest), { recursive: true });
        copyFileSync(src, dest);
        console.log(`[copy-occt-wasm] ${src} -> ${dest}`);
      } else {
        console.warn(`[copy-occt-wasm] WARN: ${src} not found; run npm install`);
      }
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [copyWasmPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
